# Generated by Django 2.1.5 on 2019-02-13 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='contact',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
