# Generated by Django 2.1.5 on 2019-02-24 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0005_auto_20190220_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertise',
            name='image',
            field=models.ImageField(default='', upload_to='expertise/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expertise',
            name='name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qualification',
            name='grade',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qualification',
            name='institution',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qualification',
            name='year',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
