# Generated by Django 2.1.5 on 2019-03-07 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0006_auto_20190224_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualification',
            name='field',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='github',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='linkedin',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='resume_pdf',
            field=models.FileField(default='', upload_to='resume/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='skype',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='twitter',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
