# Generated by Django 2.1.5 on 2019-03-09 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0008_resume_email_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='contact',
            field=models.BigIntegerField(),
        ),
    ]
